/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenerateSpecRequest } from '../../models/generate-spec-request';
import { GenerateSpecResponse } from '../../models/generate-spec-response';

export interface GenerateSpec$Params {
      body: GenerateSpecRequest
}

export function generateSpec(http: HttpClient, rootUrl: string, params: GenerateSpec$Params, context?: HttpContext): Observable<StrictHttpResponse<GenerateSpecResponse>> {
  const rb = new RequestBuilder(rootUrl, generateSpec.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenerateSpecResponse>;
    })
  );
}

generateSpec.PATH = '/api/ai/text/generate-spec';
