/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContextResponse } from '../../models/context-response';

export interface GetContext$Params {
  key: 'builder' | 'principles' | 'codebase' | 'references';
}

export function getContext(http: HttpClient, rootUrl: string, params: GetContext$Params, context?: HttpContext): Observable<StrictHttpResponse<ContextResponse>> {
  const rb = new RequestBuilder(rootUrl, getContext.PATH, 'get');
  if (params) {
    rb.path('key', params.key, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContextResponse>;
    })
  );
}

getContext.PATH = '/api/context/{key}';
