/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContextUpdateRequest } from '../../models/context-update-request';
import { SuccessResponse } from '../../models/success-response';

export interface PutContext$Params {
  key: 'builder' | 'principles' | 'codebase' | 'references';
      body: ContextUpdateRequest
}

export function putContext(http: HttpClient, rootUrl: string, params: PutContext$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponse>> {
  const rb = new RequestBuilder(rootUrl, putContext.PATH, 'put');
  if (params) {
    rb.path('key', params.key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponse>;
    })
  );
}

putContext.PATH = '/api/context/{key}';
