/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RewriteActionRequest } from '../../models/rewrite-action-request';
import { TextResponse } from '../../models/text-response';

export interface RewriteAction$Params {
      body: RewriteActionRequest
}

export function rewriteAction(http: HttpClient, rootUrl: string, params: RewriteAction$Params, context?: HttpContext): Observable<StrictHttpResponse<TextResponse>> {
  const rb = new RequestBuilder(rootUrl, rewriteAction.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TextResponse>;
    })
  );
}

rewriteAction.PATH = '/api/rewrite';
