/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUpdateRequest } from '../../models/file-update-request';
import { SuccessResponse } from '../../models/success-response';

export interface UpdateProjectFile$Params {
  id: string;
  filename: string;
      body: FileUpdateRequest
}

export function updateProjectFile(http: HttpClient, rootUrl: string, params: UpdateProjectFile$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProjectFile.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('filename', params.filename, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponse>;
    })
  );
}

updateProjectFile.PATH = '/api/projects/{id}/files/{filename}';
