/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PortalSessionResponse } from '../../models/portal-session-response';

export interface CreateBillingPortal$Params {
}

export function createBillingPortal(http: HttpClient, rootUrl: string, params?: CreateBillingPortal$Params, context?: HttpContext): Observable<StrictHttpResponse<PortalSessionResponse>> {
  const rb = new RequestBuilder(rootUrl, createBillingPortal.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PortalSessionResponse>;
    })
  );
}

createBillingPortal.PATH = '/api/billing/portal';
