/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebhookAckResponse } from '../../models/webhook-ack-response';

export interface StripeWebhook$Params {

/**
 * HMAC signature set by Stripe on every webhook delivery. Verified by service.py before any handler runs; unsigned payloads return 400. Six event types are dispatched: checkout.session.completed, customer.subscription.updated, customer.subscription.deleted, invoice.payment_failed, invoice.paid, invoice.upcoming.
 */
  'Stripe-Signature': string;
      body: {
}
}

export function stripeWebhook(http: HttpClient, rootUrl: string, params: StripeWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<WebhookAckResponse>> {
  const rb = new RequestBuilder(rootUrl, stripeWebhook.PATH, 'post');
  if (params) {
    rb.header('Stripe-Signature', params['Stripe-Signature'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebhookAckResponse>;
    })
  );
}

stripeWebhook.PATH = '/api/billing/webhook';
