/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface VerifyCheckoutSession$Params {

/**
 * Stripe Checkout session ID (cs_…).
 */
  session_id: string;
}

export function verifyCheckoutSession(http: HttpClient, rootUrl: string, params: VerifyCheckoutSession$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'plan': 'free' | 'pro';
'payment_status': string;
}>> {
  const rb = new RequestBuilder(rootUrl, verifyCheckoutSession.PATH, 'get');
  if (params) {
    rb.query('session_id', params.session_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'plan': 'free' | 'pro';
      'payment_status': string;
      }>;
    })
  );
}

verifyCheckoutSession.PATH = '/api/billing/verify-session';
