/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CancelAcceptedResponse } from '../../models/cancel-accepted-response';

export interface CancelTaskGen$Params {
  project_id: string;
}

export function cancelTaskGen(http: HttpClient, rootUrl: string, params: CancelTaskGen$Params, context?: HttpContext): Observable<StrictHttpResponse<CancelAcceptedResponse>> {
  const rb = new RequestBuilder(rootUrl, cancelTaskGen.PATH, 'post');
  if (params) {
    rb.path('project_id', params.project_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CancelAcceptedResponse>;
    })
  );
}

cancelTaskGen.PATH = '/api/projects/{project_id}/cancel';
