/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenerateTaskStatusResponse } from '../../models/generate-task-status-response';

export interface GetGenerateTaskStatus$Params {
  project_id: string;
}

export function getGenerateTaskStatus(http: HttpClient, rootUrl: string, params: GetGenerateTaskStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<GenerateTaskStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getGenerateTaskStatus.PATH, 'get');
  if (params) {
    rb.path('project_id', params.project_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenerateTaskStatusResponse>;
    })
  );
}

getGenerateTaskStatus.PATH = '/api/projects/{project_id}/generate-task/status';
