/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClaimProjectResponse } from '../../models/claim-project-response';

export interface ClaimProject$Params {

/**
 * Project slug (filesystem directory name).
 */
  id: string;
}

export function claimProject(http: HttpClient, rootUrl: string, params: ClaimProject$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimProjectResponse>> {
  const rb = new RequestBuilder(rootUrl, claimProject.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClaimProjectResponse>;
    })
  );
}

claimProject.PATH = '/api/projects/{id}/claim';
