/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileDiffResponse } from '../../models/file-diff-response';

export interface GetFileDiff$Params {
  project_id: string;
  filename: string;
  from_sha: string;
  to_sha: string;
}

export function getFileDiff(http: HttpClient, rootUrl: string, params: GetFileDiff$Params, context?: HttpContext): Observable<StrictHttpResponse<FileDiffResponse>> {
  const rb = new RequestBuilder(rootUrl, getFileDiff.PATH, 'get');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('filename', params.filename, {});
    rb.query('from_sha', params.from_sha, {});
    rb.query('to_sha', params.to_sha, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileDiffResponse>;
    })
  );
}

getFileDiff.PATH = '/api/projects/{project_id}/files/{filename}/diff';
