/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileHistoryResponse } from '../../models/file-history-response';

export interface GetFileHistory$Params {
  project_id: string;
  filename: string;
  limit?: number;
}

export function getFileHistory(http: HttpClient, rootUrl: string, params: GetFileHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<FileHistoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getFileHistory.PATH, 'get');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('filename', params.filename, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileHistoryResponse>;
    })
  );
}

getFileHistory.PATH = '/api/projects/{project_id}/files/{filename}/history';
