/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileRevertRequest } from '../../models/file-revert-request';
import { FileRevertResponse } from '../../models/file-revert-response';

export interface RevertFile$Params {
  project_id: string;
  filename: string;
      body: FileRevertRequest
}

export function revertFile(http: HttpClient, rootUrl: string, params: RevertFile$Params, context?: HttpContext): Observable<StrictHttpResponse<FileRevertResponse>> {
  const rb = new RequestBuilder(rootUrl, revertFile.PATH, 'post');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('filename', params.filename, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileRevertResponse>;
    })
  );
}

revertFile.PATH = '/api/projects/{project_id}/files/{filename}/revert';
