/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShareProjectResponse } from '../../models/share-project-response';

export interface ShareProject$Params {
  id: string;
}

export function shareProject(http: HttpClient, rootUrl: string, params: ShareProject$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareProjectResponse>> {
  const rb = new RequestBuilder(rootUrl, shareProject.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareProjectResponse>;
    })
  );
}

shareProject.PATH = '/api/projects/{id}/share';
