# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, confloat, conint, constr


class Status(Enum):
    ok = 'ok'


class HealthResponse(BaseModel):
    status: Status


class SpecSummary(BaseModel):
    filename: str
    label: str


class SpecDetail(BaseModel):
    filename: str
    label: str
    content: str


class ProjectSummary(BaseModel):
    id: str
    name: str
    createdAt: AwareDatetime
    specs: List[SpecSummary]


class ProjectDetail(BaseModel):
    id: str
    name: str
    createdAt: AwareDatetime
    specs: List[SpecDetail]


class Severity(Enum):
    error = 'error'
    warning = 'warning'
    info = 'info'


class LintBraindumpFlag(BaseModel):
    severity: Severity
    message: str


class LintBraindumpRequest(BaseModel):
    braindump: constr(min_length=1) = Field(
        ..., description='Brain dump text to analyse for spec readiness.'
    )


class LintBraindumpResponse(BaseModel):
    ready: bool
    flags: List[LintBraindumpFlag]


class Severity1(Enum):
    error = 'error'
    warning = 'warning'


class CoherenceFlag(BaseModel):
    rule: str = Field(
        ...,
        description='Invariant identifier (e.g. symbol_uniqueness, content_routing).',
    )
    severity: Severity1
    message: str
    line: Optional[int] = Field(
        None, description='1-based line number in the source document, when applicable.'
    )


class CoherenceResponse(BaseModel):
    flags: List[CoherenceFlag]
    summary: str = Field(
        ...,
        description='Human-readable count string, e.g. "3 flags: 1 error, 2 warnings."',
    )


class FileInput(BaseModel):
    filename: str
    content: str


class ProjectCreateResponse(BaseModel):
    id: str
    name: str
    createdAt: AwareDatetime


class FileUpdateRequest(BaseModel):
    content: str


class CommitEntry(BaseModel):
    sha: str
    message: str
    author: str
    timestamp: AwareDatetime


class FileHistoryResponse(BaseModel):
    history: List[CommitEntry]


class FileDiffResponse(BaseModel):
    diff: str


class FileRevertRequest(BaseModel):
    to_sha: str
    path: Optional[str] = Field(
        None,
        description="Optional alias for filename; the route's path parameter is canonical.",
    )


class FileRevertResponse(BaseModel):
    sha: str
    message: str


class SuccessResponse(BaseModel):
    success: bool


class ContextResponse(BaseModel):
    content: str
    exists: bool


class ContextUpdateRequest(BaseModel):
    content: str


class ErrorResponse(BaseModel):
    error: str


class GenerateRequest(BaseModel):
    prompt: constr(min_length=1) = Field(
        ...,
        description='Prompt text to generate from. Whitespace-only values are rejected by the server.\n',
    )
    tone: Optional[str] = Field(
        'balanced',
        description='Optional tone directive (e.g. "balanced", "formal", "casual"). Defaults to "balanced" to match the Angular client default.\n',
    )


class GenerateResponse(BaseModel):
    text: str
    latencyMs: conint(ge=0)


class RewriteRequest(BaseModel):
    text: constr(min_length=1) = Field(
        ...,
        description='Text to rewrite. Whitespace-only values are rejected by the server.',
    )
    instructions: Optional[str] = Field(
        '',
        description='Optional rewrite instruction. Empty string means clean rewrite.',
    )


class RewriteResponse(BaseModel):
    text: str
    latencyMs: conint(ge=0)


class GenerateSpecRequest(BaseModel):
    input: constr(min_length=1) = Field(
        ...,
        description='Brain dump text. Whitespace-only values are rejected by the server.',
    )


class GenerateSpecResponse(BaseModel):
    text: str = Field(
        ...,
        description='Raw multi-file output with ===FILE: filename=== markers. Not JSON-wrapped. The Angular parser splits on this exact string; wrapping breaks the parser.\n',
    )
    latencyMs: conint(ge=0)


class IterateRequest(BaseModel):
    document: constr(min_length=1) = Field(
        ...,
        description='Document content to iterate on. Whitespace-only values are rejected by the server.\n',
    )
    instruction: Optional[str] = Field(
        '',
        description='Optional editing instruction. Empty string means clean/improve with no specific directive.\n',
    )


class IterateResponse(BaseModel):
    text: str
    latencyMs: conint(ge=0)


class ReviewRequest(BaseModel):
    documents: Dict[str, str] = Field(
        ..., description='Map of document name to content.'
    )


class ReviewResponse(BaseModel):
    scores: Dict[str, float] = Field(
        ...,
        description='Quality scores keyed by dimension (clarity, completeness, etc.)',
    )
    issues: List[str] = Field(..., description='List of issues found in the documents.')


class BootstrapProjectRequest(BaseModel):
    project_name: constr(min_length=1)
    braindump: constr(min_length=1)
    builder: Optional[str] = ''
    principles: Optional[str] = ''
    codebase: Optional[str] = ''
    references: Optional[str] = ''


class BootstrapFile(BaseModel):
    filename: str
    content: str


class BootstrapProjectResponse(BaseModel):
    files: List[BootstrapFile]
    latencyMs: conint(ge=0)


class BootstrapStartResponse(BaseModel):
    job_id: str = Field(
        ...,
        description='Opaque job identifier. Pass to GET /bootstrap-project/status/{job_id} to poll for completion. The job is evicted from the server on the first terminal (done=true) read.\n',
    )


class BootstrapJobStatus(BaseModel):
    running: bool = Field(
        ..., description='True while the background chain is in progress.'
    )
    done: bool = Field(
        ..., description='True once the job has terminated (successfully or not).'
    )
    current_step: Optional[str] = Field(
        None,
        description='Name of the workflow step currently being driven by the runtime, or null between iterations and after the workflow completes.\n',
    )
    partial: Optional[str] = Field(
        None,
        description='Rolling 500-char tail of the in-flight step\'s streamed output. Empty string when the current step does not stream or has not yet produced any chunks. Read from execution.outputs["_partials"][current_step].\n',
    )
    warnings: Optional[List[str]] = Field(
        None,
        description='Per-execution warnings accumulated by the truncation heuristic after each successful step. Empty array means clean output. The status route always populates this; consumers may rely on it.\n',
    )
    status: Optional[str] = Field(
        None,
        description='Terminal status indicator, present only on terminal CANCELLED reads. Successful and errored reads do not populate this field.\n',
    )
    files: Optional[List[BootstrapFile]] = Field(
        None,
        description='Output files produced by the bootstrap run. Present only on success.',
    )
    error: Optional[str] = Field(
        None,
        description='Error message captured from the background job. Present only on failure.',
    )
    latencyMs: Optional[conint(ge=0)] = Field(
        None, description='Wall-clock milliseconds from job start to completion.'
    )


class CancelAcceptedResponse(BaseModel):
    status: str = Field(
        ...,
        description='Current execution status string after the request.',
        examples=['CANCELLING'],
    )


class Step(Enum):
    analysis = 'analysis'
    epic = 'epic'
    architecture = 'architecture'


class RetryBootstrapRequest(BaseModel):
    step: Step = Field(
        ...,
        description="Bootstrap sub-step to retry. Each maps to a Rel-T3 sub-workflow (spec_gen/bootstrap-{step}-only) that re-uses the prior run's upstream outputs as inputs.\n",
    )


class RegenerateTaskRequest(BaseModel):
    task_num: str = Field(
        ...,
        description='Task number whose generated guide should be deleted and re-generated. Matches the num column in the epic backlog.\n',
    )


class TimelineTask(BaseModel):
    num: str = Field(
        ..., description='Task number as it appears in the epic backlog row.'
    )
    name: str = Field(..., description='Task name (without bold markers).')
    effort: str = Field(
        ..., description='Effort estimate column from the epic backlog row.'
    )


class TimelineRequest(BaseModel):
    project_name: constr(min_length=1)
    tasks: List[TimelineTask]


class TemplateResponse(BaseModel):
    content: str = Field(..., description='Generated markdown string.')


class GenerateTaskStartResponse(BaseModel):
    started: bool = Field(
        ...,
        description='True if a new background thread was spawned, false if one was already running.',
    )
    alreadyRunning: Optional[bool] = Field(
        None,
        description='Present and true when a generation thread for this project was already running.',
    )


class LintFlag(BaseModel):
    rule: str = Field(
        ..., description='Lint rule identifier (e.g. "personal-path", "preamble-leak").'
    )
    severity: Severity1 = Field(
        ...,
        description='"error" blocks the write; "warning" allows it with the flag surfaced.',
    )
    message: str = Field(..., description='Human-readable violation description.')
    line: Optional[int] = Field(
        None, description='1-based line number of the first violation site, if known.'
    )


class RepairProjectResponse(BaseModel):
    repaired: List[str] = Field(
        ...,
        description='Filenames written during this repair run. Empty array means all structural files were already present.\n',
    )


class Feature(Enum):
    bootstrap = 'bootstrap'
    task_gen = 'task_gen'
    spec_gen = 'spec_gen'


class UsageLimitError(BaseModel):
    error: str = Field(
        ...,
        description='Stable error code for client dispatch.',
        examples=['free_tier_limit_reached'],
    )
    feature: Feature = Field(
        ...,
        description='Feature key that hit the daily cap. Matches keys in DAILY_FREE_TIER_LIMITS in modules/usage/service.py.\n',
        examples=['task_gen'],
    )
    limit: conint(ge=0) = Field(
        ...,
        description='Daily cap for this feature on the free tier. Free-tier caps are bootstrap=3 / task_gen=20 / spec_gen=10 per UTC day.\n',
        examples=[20],
    )
    reset_at: AwareDatetime = Field(
        ...,
        description='UTC midnight at which the daily counter resets.',
        examples=['2026-04-27T00:00:00Z'],
    )
    upgrade_url: str = Field(
        ...,
        description="App-relative path to the upgrade page. Angular's 429 interceptor navigates to this URL when a UsageLimitError is received.\n",
        examples=['/upgrade'],
    )


class CheckoutSessionResponse(BaseModel):
    url: str = Field(
        ...,
        description='Stripe-hosted checkout URL. Redirect the browser to this value. Valid for a single checkout attempt; do not cache.\n',
        examples=['https://checkout.stripe.com/pay/cs_test_xxx'],
    )


class WebhookAckResponse(BaseModel):
    received: bool = Field(
        ...,
        description='Always true on a 200 response. Signals Stripe that the payload was accepted; Stripe will not retry.\n',
        examples=[True],
    )


class Plan(Enum):
    free = 'free'
    pro = 'pro'


class Status1(Enum):
    active = 'active'
    past_due = 'past_due'
    canceled = 'canceled'


class BillingStatusResponse(BaseModel):
    plan: Plan = Field(
        ...,
        description="Current plan. Written exclusively by Stripe webhook handlers; no in-app code path may set this to 'pro'.\n",
        examples=['free'],
    )
    status: Optional[Status1] = Field(
        None,
        description="Stripe subscription status. Null for free users who have never subscribed. Note: per the past-due policy, status=past_due on invoice.payment_failed reverts plan to 'free' immediately.\n",
        examples=['active'],
    )
    current_period_end: Optional[AwareDatetime] = Field(
        None,
        description='End of the current billing period. Null for free users.\n',
        examples=['2026-05-26T00:00:00Z'],
    )
    manage_url: Optional[str] = Field(
        None,
        description='Live Stripe Customer Portal URL. Generated per-request (Stripe session tokens expire). Null until the user completes their first checkout session; the customer ID is created lazily.\n',
        examples=['https://billing.stripe.com/p/session/xxx'],
    )


class Status2(Enum):
    ok = 'ok'
    degraded = 'degraded'
    skipped = 'skipped'


class HealthStatus(BaseModel):
    status: Status2
    error: Optional[str] = Field(
        None,
        description='Truncated upstream error message (max 100 chars). Present only when status=degraded.\n',
    )


class AiStatsResponse(BaseModel):
    calls: conint(ge=0)
    input_tokens: conint(ge=0)
    output_tokens: conint(ge=0)
    cost_usd: confloat(ge=0.0)
    provider: str = Field(..., description='Resolved provider name at request time.')


class MagicLinkRequest(BaseModel):
    email: EmailStr = Field(
        ..., description='Address that will receive the magic-link email.'
    )


class MagicLinkResponse(BaseModel):
    request_id: str = Field(
        ...,
        description='Opaque identifier returned by Neon Auth for the dispatched magic-link request. Useful for support diagnostics.\n',
    )


class VerifyRequest(BaseModel):
    token: str = Field(
        ..., description='One-time token extracted from the magic-link URL fragment.'
    )


class MeResponse(BaseModel):
    id: int = Field(..., description='Spec-doc internal user row id.')
    email: str = Field(..., description='User email (mirrors the Neon Auth claim).')
    auth_user_id: str = Field(
        ...,
        description='Stable identity from Neon Auth (sub claim). FK anchor for every tenant-scoped table in saas-persistence.\n',
    )


class ProjectCreateRequest(BaseModel):
    name: str
    files: List[FileInput]


class GenerateTaskStatusResponse(BaseModel):
    running: bool = Field(
        ..., description='True while the background thread is in progress.'
    )
    done: bool = Field(
        ..., description='True once the thread has terminated (successfully or not).'
    )
    allDone: Optional[bool] = Field(
        None,
        description='Present and true when every task in the epic already has a matching guide on disk.',
    )
    filename: Optional[str] = Field(
        None,
        description='Name of the task-N-*.md file that was written (only when done and not allDone).',
    )
    taskNum: Optional[str] = Field(
        None, description='Task number from the epic table (e.g., "2").'
    )
    taskName: Optional[str] = Field(None, description='Task name from the epic table.')
    error: Optional[str] = Field(
        None, description='Error message captured from the background thread.'
    )
    lintErrors: Optional[List[LintFlag]] = Field(
        None,
        description='Present when error-severity lint flags blocked the file write. The polling route returns 502 when this field is present.\n',
    )
    warnings: Optional[List[LintFlag]] = Field(
        None,
        description='Present when warning-severity lint flags were raised but the file was still written successfully.\n',
    )


class VerifyResponse(BaseModel):
    jwt: str = Field(
        ...,
        description='Session JWT issued by Neon Auth. Pass as Authorization Bearer.',
    )
    user: MeResponse
