/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Org-wide cumulative AI usage and cost since process start. Resets on restart; sourced from the in-process accumulator in runtime/chain/adapter.py.
 */
export interface AiStatsResponse {
  calls: number;
  cost_usd: number;
  input_tokens: number;
  output_tokens: number;

  /**
   * Resolved provider name at request time.
   */
  provider: string;
}
