/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Subscription snapshot for the authenticated user. plan is always present; the other fields are null for free users who have never completed a checkout.
 */
export interface BillingStatusResponse {

  /**
   * End of the current billing period. Null for free users.
   */
  current_period_end?: string | null;

  /**
   * Live Stripe Customer Portal URL. Generated per-request (Stripe session tokens expire). Null until the user completes their first checkout session; the customer ID is created lazily.
   */
  manage_url?: string | null;

  /**
   * Current plan. Written exclusively by Stripe webhook handlers; no in-app code path may set this to 'pro'.
   */
  plan: 'free' | 'pro';

  /**
   * Stripe subscription status. Null for free users who have never subscribed. Note: per the past-due policy, status=past_due on invoice.payment_failed reverts plan to 'free' immediately.
   */
  status?: ('active' | 'past_due' | 'canceled') | null;
}
