/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BootstrapFile } from '../models/bootstrap-file';

/**
 * Status snapshot returned by GET /bootstrap-project/status/{job_id}. Mirrors the GenerateTaskStatusResponse shape for Angular polling parity. The 'files', 'error', and 'latencyMs' fields are present only when the job has reached a terminal state.
 */
export interface BootstrapJobStatus {

  /**
   * Name of the workflow step currently being driven by the runtime, or null between iterations and after the workflow completes.
   */
  current_step?: string | null;

  /**
   * True once the job has terminated (successfully or not).
   */
  done: boolean;

  /**
   * Error message captured from the background job. Present only on failure.
   */
  error?: string;

  /**
   * Output files produced by the bootstrap run. Present only on success.
   */
  files?: Array<BootstrapFile>;

  /**
   * Wall-clock milliseconds from job start to completion.
   */
  latencyMs?: number;

  /**
   * Rolling 500-char tail of the in-flight step's streamed output. Empty string when the current step does not stream or has not yet produced any chunks. Read from execution.outputs["_partials"][current_step].
   */
  partial?: string;

  /**
   * True while the background chain is in progress.
   */
  running: boolean;

  /**
   * Terminal status indicator, present only on terminal CANCELLED reads. Successful and errored reads do not populate this field.
   */
  status?: string;

  /**
   * Per-execution warnings accumulated by the truncation heuristic after each successful step. Empty array means clean output. The status route always populates this; consumers may rely on it.
   */
  warnings?: Array<string>;
}
