/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BootstrapFile } from '../models/bootstrap-file';
export interface BootstrapProjectResponse {
  files: Array<BootstrapFile>;
  latencyMs: number;
}
