/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BootstrapProjectRequest {
  braindump: string;
  builder?: string;
  codebase?: string;
  principles?: string;
  project_name: string;
  references?: string;
}
