/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Immediate 202 acknowledgement from POST /api/ai/text/bootstrap-project.
 */
export interface BootstrapStartResponse {

  /**
   * Opaque job identifier. Pass to GET /bootstrap-project/status/{job_id} to poll for completion. The job is evicted from the server on the first terminal (done=true) read.
   */
  job_id: string;
}
