/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Returned with HTTP 202 by the cancel routes once the WorkflowExecution has been flipped to CANCELLING. Final CANCELLED transition happens between step boundaries on the runtime's next iteration.
 */
export interface CancelAcceptedResponse {

  /**
   * Current execution status string after the request.
   */
  status: string;
}
