/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckoutSessionResponse {

  /**
   * Stripe-hosted checkout URL. Redirect the browser to this value. Valid for a single checkout attempt; do not cache.
   */
  url: string;
}
