/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Optional product + plan selector. Defaults to oll_pro / monthly when omitted. Each (product, plan) pair resolves to a Stripe price via the STRIPE_PRICE_{PRODUCT}_{PLAN} env convention.
 */
export interface CheckoutSessionRequest {

  /**
   * Billing interval / variant.
   */
  plan?: 'monthly' | 'yearly' | 'one_time';

  /**
   * Product slug (e.g. oll_pro, headshot_chf29).
   */
  product?: string;
}
