/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClaimProjectResponse {

  /**
   * Always true on a successful claim.
   */
  claimed: boolean;

  /**
   * Project slug (filesystem directory name).
   */
  id: string;
}
