/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CoherenceFlag {

  /**
   * 1-based line number in the source document, when applicable.
   */
  line?: number;
  message: string;

  /**
   * Invariant identifier (e.g. symbol_uniqueness, content_routing).
   */
  rule: string;
  severity: 'error' | 'warning';
}
