/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CoherenceFlag } from '../models/coherence-flag';
export interface CoherenceResponse {
  flags: Array<CoherenceFlag>;

  /**
   * Human-readable count string, e.g. "3 flags: 1 error, 2 warnings."
   */
  summary: string;
}
