/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailSendResponse {

  /**
   * True when the provider accepted the message for delivery.
   */
  sent: boolean;
}
