/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Transactional email request. The recipient is scoped server-side to the authenticated user's own address; the `to` field must match it.
 */
export interface EmailSendRequest {

  /**
   * Template-specific context (e.g. plan, product, order_id, link).
   */
  ctx?: {
[key: string]: any;
};

  /**
   * Required when template is 'custom'.
   */
  html?: string;

  /**
   * Required when template is 'custom'.
   */
  subject?: string;

  /**
   * Named template to render, or 'custom' to pass subject + html directly.
   */
  template: 'subscription_activated' | 'subscription_canceled' | 'payment_failed' | 'magic_link' | 'order_confirmation' | 'custom';

  /**
   * Recipient address. Must equal the authenticated user's own email; arbitrary recipients are rejected with 403.
   */
  to: string;
}
