/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileRevertRequest {

  /**
   * Optional alias for filename; the route's path parameter is canonical.
   */
  path?: string;
  to_sha: string;
}
