/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitEntry } from '../models/commit-entry';
export interface FileHistoryResponse {
  history: Array<CommitEntry>;
}
