/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateRequest {

  /**
   * Prompt text to generate from. Whitespace-only values are rejected by the server.
   */
  prompt: string;

  /**
   * Optional tone directive (e.g. "balanced", "formal", "casual"). Defaults to "balanced" to match the Angular client default.
   */
  tone?: string;
}
