/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateTaskStartResponse {

  /**
   * Present and true when a generation thread for this project was already running.
   */
  alreadyRunning?: boolean;

  /**
   * True if a new background thread was spawned, false if one was already running.
   */
  started: boolean;
}
