/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateSpecRequest {

  /**
   * Brain dump text. Whitespace-only values are rejected by the server.
   */
  input: string;
}
