/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateSpecResponse {
  latencyMs: number;

  /**
   * Raw multi-file output with ===FILE: filename=== markers. Not JSON-wrapped. The Angular parser splits on this exact string; wrapping breaks the parser.
   */
  text: string;
}
