/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LintFlag } from '../models/lint-flag';
export interface GenerateTaskStatusResponse {

  /**
   * Present and true when every task in the epic already has a matching guide on disk.
   */
  allDone?: boolean;

  /**
   * True once the thread has terminated (successfully or not).
   */
  done: boolean;

  /**
   * Error message captured from the background thread.
   */
  error?: string;

  /**
   * Name of the task-N-*.md file that was written (only when done and not allDone).
   */
  filename?: string;

  /**
   * Present when error-severity lint flags blocked the file write. The polling route returns 502 when this field is present.
   */
  lintErrors?: Array<LintFlag>;

  /**
   * True while the background thread is in progress.
   */
  running: boolean;

  /**
   * Task name from the epic table.
   */
  taskName?: string;

  /**
   * Task number from the epic table (e.g., "2").
   */
  taskNum?: string;

  /**
   * Present when warning-severity lint flags were raised but the file was still written successfully.
   */
  warnings?: Array<LintFlag>;
}
