/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Per-dependency health probe response returned by the /api/health/{anthropic,neon,stripe} routes. status=ok means the dependency is reachable; status=skipped means the probe is intentionally not run (env var unset, or a permanently stubbed dep); status=degraded means the probe failed and an error string is included.
 */
export interface HealthStatus {

  /**
   * Truncated upstream error message (max 100 chars). Present only when status=degraded.
   */
  error?: string;
  status: 'ok' | 'degraded' | 'skipped';
}
