/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IterateRequest {

  /**
   * Document content to iterate on. Whitespace-only values are rejected by the server.
   */
  document: string;

  /**
   * Optional editing instruction. Empty string means clean/improve with no specific directive.
   */
  instruction?: string;
}
