/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LintBraindumpFlag } from '../models/lint-braindump-flag';
export interface LintBraindumpResponse {
  flags: Array<LintBraindumpFlag>;
  ready: boolean;
}
