/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LintBraindumpRequest {

  /**
   * Brain dump text to analyse for spec readiness.
   */
  braindump: string;
}
