/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LintFlag {

  /**
   * 1-based line number of the first violation site, if known.
   */
  line?: number | null;

  /**
   * Human-readable violation description.
   */
  message: string;

  /**
   * Lint rule identifier (e.g. "personal-path", "preamble-leak").
   */
  rule: string;

  /**
   * "error" blocks the write; "warning" allows it with the flag surfaced.
   */
  severity: 'error' | 'warning';
}
