/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MagicLinkResponse {

  /**
   * Always true on a 200 response. Does not reveal whether an account exists for the address (anti-enumeration).
   */
  sent: boolean;
}
