/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MagicLinkResponse {

  /**
   * Opaque identifier returned by Neon Auth for the dispatched magic-link request. Useful for support diagnostics.
   */
  request_id: string;
}
