/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {

  /**
   * Canonical email of the authenticated user.
   */
  email: string;

  /**
   * Spec-doc internal user row id.
   */
  id: number;

  /**
   * Current account plan. Written exclusively by Stripe webhook handlers; no in-app code path may set this to 'pro'.
   */
  plan: 'free' | 'pro' | 'lapsed';

  /**
   * ISO 8601 UTC expiry of the bearer token presented on this request. Null when the expiry cannot be decoded.
   */
  token_expires_at?: string | null;
}
