/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {

  /**
   * Stable identity from Neon Auth (sub claim). FK anchor for every tenant-scoped table in saas-persistence.
   */
  auth_user_id: string;

  /**
   * User email (mirrors the Neon Auth claim).
   */
  email: string;

  /**
   * Spec-doc internal user row id.
   */
  id: number;
}
