/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PortalSessionResponse {

  /**
   * Live Stripe Customer Portal URL for self-service subscription management. Generated per-request; do not cache.
   */
  url: string;
}
