/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpecSummary } from '../models/spec-summary';
export interface ProjectSummary {
  createdAt: string;
  id: string;
  name: string;
  specs: Array<SpecSummary>;
}
