/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpecDetail } from '../models/spec-detail';
export interface ProjectDetail {
  createdAt: string;
  id: string;
  name: string;
  specs: Array<SpecDetail>;
}
