/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileInput } from '../models/file-input';
export interface ProjectCreateRequest {
  files: Array<FileInput>;
  name: string;
}
