/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicAnalyzeJobStatus {

  /**
   * Generated analysis markdown. Present only on success.
   */
  analysis?: string | null;

  /**
   * Original braindump text submitted by the caller.
   */
  braindump?: string | null;

  /**
   * True once the job has terminated (successfully or not).
   */
  done: boolean;

  /**
   * Error message from the background job. Present only on failure.
   */
  error?: string | null;

  /**
   * Project slug created for this anonymous analysis. Identical to the job_id.
   */
  project_id?: string | null;

  /**
   * True while the background analysis is in progress.
   */
  running: boolean;

  /**
   * Public share slug for the created project. Use with GET /api/public/share/{slug}.
   */
  share_slug?: string | null;
}
