/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicDoc } from '../models/public-doc';
export interface PublicSpecResponse {
  docs: Array<PublicDoc>;

  /**
   * Internal project slug (filesystem directory name).
   */
  id: string;

  /**
   * Human-readable project name.
   */
  name: string;
}
