/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegenerateTaskRequest {

  /**
   * Task number whose generated guide should be deleted and re-generated. Matches the num column in the epic backlog.
   */
  task_num: string;
}
