/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RetryBootstrapRequest {

  /**
   * Bootstrap sub-step to retry. Each maps to a Rel-T3 sub-workflow (spec_gen/bootstrap-{step}-only) that re-uses the prior run's upstream outputs as inputs.
   */
  step: 'analysis' | 'epic' | 'architecture';
}
