/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewRequest {

  /**
   * Map of document name to content.
   */
  documents: {
[key: string]: string;
};
}
