/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponse {

  /**
   * List of issues found in the documents.
   */
  issues: Array<string>;

  /**
   * Quality scores keyed by dimension (clarity, completeness, etc.)
   */
  scores: {
[key: string]: number;
};
}
