/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RewriteActionRequest {
  style: 'Concise' | 'Technical' | 'Executive' | 'Narrative' | 'Punchy';
  text: string;
}
