/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RewriteRequest {

  /**
   * Optional rewrite instruction. Empty string means clean rewrite.
   */
  instructions?: string;

  /**
   * Text to rewrite. Whitespace-only values are rejected by the server.
   */
  text: string;
}
