/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SecurityHealthResponse {

  /**
   * Human-readable description of the misconfiguration. Present only when status=misconfigured.
   */
  error?: string;

  /**
   * Value of FLASK_ENV at probe time. Present only when status=misconfigured.
   */
  flask_env?: string;

  /**
   * True when SKIP_AUTH is active and the environment is development (acceptable). Present only on a 200 response.
   */
  skip_auth_bypassed?: boolean;
  status: 'ok' | 'misconfigured';
}
