/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShareProjectResponse {

  /**
   * Short url-safe slug for the shared project.
   */
  shareSlug: string;

  /**
   * App-relative URL for the public view (e.g. /s/abc123).
   */
  url: string;
}
