/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimelineTask } from '../models/timeline-task';
export interface TimelineRequest {
  project_name: string;
  tasks: Array<TimelineTask>;
}
