/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimelineTask {

  /**
   * Effort estimate column from the epic backlog row.
   */
  effort: string;

  /**
   * Task name (without bold markers).
   */
  name: string;

  /**
   * Task number as it appears in the epic backlog row.
   */
  num: string;
}
