/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Returned with HTTP 429 by any AI route gated by check_usage_limit when a free-tier user has exhausted their daily quota for that feature. The Angular usage-limit interceptor catches this body globally and routes the user to upgrade_url.
 */
export interface UsageLimitError {

  /**
   * Stable error code for client dispatch.
   */
  error: string;

  /**
   * Feature key that hit the daily cap. Matches keys in DAILY_FREE_TIER_LIMITS in modules/usage/service.py.
   */
  feature: 'bootstrap' | 'task_gen' | 'spec_gen';

  /**
   * Daily cap for this feature on the free tier. Free-tier caps are bootstrap=3 / task_gen=20 / spec_gen=10 per UTC day.
   */
  limit: number;

  /**
   * UTC midnight at which the daily counter resets.
   */
  reset_at: string;

  /**
   * App-relative path to the upgrade page. Angular's 429 interceptor navigates to this URL when a UsageLimitError is received.
   */
  upgrade_url: string;
}
