/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerifyRequest {

  /**
   * One-time token extracted from the magic-link URL fragment.
   */
  token: string;
}
