/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerifyResponse {

  /**
   * Canonical email of the authenticated user.
   */
  email: string;

  /**
   * Signed JWT for use as Authorization Bearer.
   */
  token: string;
}
