/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeResponse } from '../models/me-response';
export interface VerifyResponse {

  /**
   * Session JWT issued by Neon Auth. Pass as Authorization Bearer.
   */
  jwt: string;
  user: MeResponse;
}
