/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WebhookAckResponse {

  /**
   * Always true on a 200 response. Signals Stripe that the payload was accepted; Stripe will not retry.
   */
  received: boolean;
}
