/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BootstrapProjectRequest } from '../../models/bootstrap-project-request';
import { BootstrapStartResponse } from '../../models/bootstrap-start-response';

export interface AnonymousBootstrapProject$Params {
      body: BootstrapProjectRequest
}

export function anonymousBootstrapProject(http: HttpClient, rootUrl: string, params: AnonymousBootstrapProject$Params, context?: HttpContext): Observable<StrictHttpResponse<BootstrapStartResponse>> {
  const rb = new RequestBuilder(rootUrl, anonymousBootstrapProject.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BootstrapStartResponse>;
    })
  );
}

anonymousBootstrapProject.PATH = '/api/ai/text/anonymous/bootstrap-project';
