/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenerateRequest } from '../../models/generate-request';
import { GenerateResponse } from '../../models/generate-response';

export interface GenerateText$Params {
      body: GenerateRequest
}

export function generateText(http: HttpClient, rootUrl: string, params: GenerateText$Params, context?: HttpContext): Observable<StrictHttpResponse<GenerateResponse>> {
  const rb = new RequestBuilder(rootUrl, generateText.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenerateResponse>;
    })
  );
}

generateText.PATH = '/api/ai/text/generate';
