/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BootstrapJobStatus } from '../../models/bootstrap-job-status';

export interface GetAnonymousBootstrapProjectStatus$Params {
  job_id: string;
}

export function getAnonymousBootstrapProjectStatus(http: HttpClient, rootUrl: string, params: GetAnonymousBootstrapProjectStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<BootstrapJobStatus>> {
  const rb = new RequestBuilder(rootUrl, getAnonymousBootstrapProjectStatus.PATH, 'get');
  if (params) {
    rb.path('job_id', params.job_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BootstrapJobStatus>;
    })
  );
}

getAnonymousBootstrapProjectStatus.PATH = '/api/ai/text/anonymous/bootstrap-project/status/{job_id}';
