/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiStatsResponse } from '../../models/ai-stats-response';

export interface GetAiStats$Params {
}

export function getAiStats(http: HttpClient, rootUrl: string, params?: GetAiStats$Params, context?: HttpContext): Observable<StrictHttpResponse<AiStatsResponse>> {
  const rb = new RequestBuilder(rootUrl, getAiStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiStatsResponse>;
    })
  );
}

getAiStats.PATH = '/api/ai/stats';
