/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BootstrapStartResponse } from '../../models/bootstrap-start-response';
import { RetryBootstrapRequest } from '../../models/retry-bootstrap-request';

export interface RetryBootstrap$Params {
  job_id: string;
      body: RetryBootstrapRequest
}

export function retryBootstrap(http: HttpClient, rootUrl: string, params: RetryBootstrap$Params, context?: HttpContext): Observable<StrictHttpResponse<BootstrapStartResponse>> {
  const rb = new RequestBuilder(rootUrl, retryBootstrap.PATH, 'post');
  if (params) {
    rb.path('job_id', params.job_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BootstrapStartResponse>;
    })
  );
}

retryBootstrap.PATH = '/api/ai/text/bootstrap-project/{job_id}/retry';
