/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CoherenceResponse } from '../../models/coherence-response';

export interface RunProjectCoherence$Params {
  id: string;
}

export function runProjectCoherence(http: HttpClient, rootUrl: string, params: RunProjectCoherence$Params, context?: HttpContext): Observable<StrictHttpResponse<CoherenceResponse>> {
  const rb = new RequestBuilder(rootUrl, runProjectCoherence.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CoherenceResponse>;
    })
  );
}

runProjectCoherence.PATH = '/api/projects/{id}/coherence';
