/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicSpecResponse } from '../../models/public-spec-response';

export interface GetPublicSpec$Params {

/**
 * Share slug generated by POST /api/projects/{id}/share.
 */
  slug: string;
}

export function getPublicSpec(http: HttpClient, rootUrl: string, params: GetPublicSpec$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicSpecResponse>> {
  const rb = new RequestBuilder(rootUrl, getPublicSpec.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicSpecResponse>;
    })
  );
}

getPublicSpec.PATH = '/api/public/share/{slug}';
