/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicAnalyzeJobStatus } from '../../models/public-analyze-job-status';

export interface GetPublicAnalysisStatus$Params {

/**
 * Job identifier returned by POST /api/public/analyze.
 */
  job_id: string;
}

export function getPublicAnalysisStatus(http: HttpClient, rootUrl: string, params: GetPublicAnalysisStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicAnalyzeJobStatus>> {
  const rb = new RequestBuilder(rootUrl, getPublicAnalysisStatus.PATH, 'get');
  if (params) {
    rb.path('job_id', params.job_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicAnalyzeJobStatus>;
    })
  );
}

getPublicAnalysisStatus.PATH = '/api/public/analyze/{job_id}';
