/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicAnalyzeRequest } from '../../models/public-analyze-request';

export interface StartPublicAnalysis$Params {
      body: PublicAnalyzeRequest
}

export function startPublicAnalysis(http: HttpClient, rootUrl: string, params: StartPublicAnalysis$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Opaque job identifier. Pass to GET /api/public/analyze/{job_id} to poll for completion.
 */
'job_id': string;

/**
 * Project slug created for this anonymous analysis. Identical to job_id.
 */
'project_id': string;

/**
 * Public share slug for the created project. Pass as ?share=<slug> to the app to load the project.
 */
'share_slug'?: string | null;
}>> {
  const rb = new RequestBuilder(rootUrl, startPublicAnalysis.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      
      /**
       * Opaque job identifier. Pass to GET /api/public/analyze/{job_id} to poll for completion.
       */
      'job_id': string;
      
      /**
       * Project slug created for this anonymous analysis. Identical to job_id.
       */
      'project_id': string;
      
      /**
       * Public share slug for the created project. Pass as ?share=<slug> to the app to load the project.
       */
      'share_slug'?: string | null;
      }>;
    })
  );
}

startPublicAnalysis.PATH = '/api/public/analyze';
