/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponse } from '../../models/success-response';

export interface DisconnectGithub$Params {
}

export function disconnectGithub(http: HttpClient, rootUrl: string, params?: DisconnectGithub$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponse>> {
  const rb = new RequestBuilder(rootUrl, disconnectGithub.PATH, 'delete');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponse>;
    })
  );
}

disconnectGithub.PATH = '/api/github/connection';
