/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GithubStatusResponse } from '../../models/github-status-response';

export interface GetGithubStatus$Params {
}

export function getGithubStatus(http: HttpClient, rootUrl: string, params?: GetGithubStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<GithubStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getGithubStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GithubStatusResponse>;
    })
  );
}

getGithubStatus.PATH = '/api/github/status';
