/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GithubCallback$Params {

/**
 * Numeric installation ID assigned by GitHub.
 */
  installation_id: string;

/**
 * Action that triggered the callback.
 */
  setup_action?: 'install' | 'update' | 'delete';
}

export function githubCallback(http: HttpClient, rootUrl: string, params: GithubCallback$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, githubCallback.PATH, 'get');
  if (params) {
    rb.query('installation_id', params.installation_id, {});
    rb.query('setup_action', params.setup_action, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

githubCallback.PATH = '/api/github/callback';
