/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BootstrapProjectRequest } from '../../models/bootstrap-project-request';
import { BootstrapProjectResponse } from '../../models/bootstrap-project-response';

export interface SpecGenGenerate$Params {
      body: BootstrapProjectRequest
}

export function specGenGenerate(http: HttpClient, rootUrl: string, params: SpecGenGenerate$Params, context?: HttpContext): Observable<StrictHttpResponse<BootstrapProjectResponse>> {
  const rb = new RequestBuilder(rootUrl, specGenGenerate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BootstrapProjectResponse>;
    })
  );
}

specGenGenerate.PATH = '/api/spec-gen/generate';
