/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthStatus } from '../../models/health-status';

export interface HealthStripe$Params {
}

export function healthStripe(http: HttpClient, rootUrl: string, params?: HealthStripe$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthStatus>> {
  const rb = new RequestBuilder(rootUrl, healthStripe.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthStatus>;
    })
  );
}

healthStripe.PATH = '/api/health/stripe';
