/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthStatus } from '../../models/health-status';

export interface HealthNeon$Params {
}

export function healthNeon(http: HttpClient, rootUrl: string, params?: HealthNeon$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthStatus>> {
  const rb = new RequestBuilder(rootUrl, healthNeon.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthStatus>;
    })
  );
}

healthNeon.PATH = '/api/health/neon';
